title: Cait Martin Newnham

description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://helloiamcait.github.io

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.svg"

aux_links: # remove if you don't want this link to appear on your pages
  Website Repository: https://github.com/helloiamcait

# External navigation links
nav_external_links:
  - title: My GitHub
    url: https://github.com/helloiamcait
    hide_icon: false # set to true to hide the external link icon - defaults to false

callouts:
  warning:
    title: Warning
    color: red